export default {
  planList: [
    { plan_id: 'supporter_0', selected: false, amount: 0, label: 'FREE' },
    { plan_id: 'starter_10', selected: false, amount: 10, label: 'Starter' },
    { plan_id: 'wise_25', selected: true, amount: 25, label: 'Wise' },
    { plan_id: 'wise_50', selected: false, amount: 50, label: 'Wise Team' },
    { plan_id: 'wise_75', selected: false, amount: 75, label: 'Wise Team PRO' },
    { plan_id: 'mentored_250', selected: false, amount: 250, label: 'Mentored' },
  ],
  featureList: [
    { amount: 0, label: 'You get access to all the published and released videos' },
    { amount: 10, label: 'You get access to all the published videos of starter level without having to wait for them to be released' },
    { amount: 25, label: 'You get access to all the published videos of starter and junior level without having to wait for them to be released' },
    { amount: 50, label: 'You get access to all the published videos of starter, junior and mid level without having to wait for them to be released' },
    { amount: 75, label: 'You get your own personalised your_name@codetap.academy email' },
    { amount: 75, label: 'You get access to all the published videos of starter, junior, mid and senior level without having to wait for them to be released' },
    { amount: 75, label: 'You get to see the videos as soon as we press the STOP RECORD button' },
    { amount: 75, label: 'You get manual personalised recommendation from your mentor when employers ask for references' },
    { amount: 75, label: 'You get invited into our team where you can work with the other students of this level as well as the ones mentored by CodeTap Academy and attend internal meetings and trainings' },
    { amount: 250, label: 'You get a dedicated mentor for 1 to 1 sessions' },
    { amount: 250, label: 'You will be guided to progress quicker and helped to understand better' },
    { amount: 250, label: 'You will get assigned on group or individual projects' },
    { amount: 250, label: 'You get unlock the extra option to be helped to get hired as quickly as possible and super boost your career' },
  ],
}